// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuwkbbakggpdvmvjknxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1d2tiYmFrZ2dwZHZtdmprbnhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNzUyNjUsImV4cCI6MjA2NzY1MTI2NX0.zIb4Om9v9jiZMwkRrlsqFwi7ecuH2hCdVGafSn5F4OE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});